# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 06:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20160623_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='prs',
        ),
        migrations.AddField(
            model_name='mark',
            name='person',
            field=models.ForeignKey(default=datetime.datetime(2016, 6, 23, 6, 25, 11, 30216, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='app1.Person'),
            preserve_default=False,
        ),
    ]
